# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminWindow_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 692)
        MainWindow.setStyleSheet("background-color: rgb(255, 230, 229);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChooseDataComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ChooseDataComboBox.setGeometry(QtCore.QRect(20, 20, 1081, 31))
        self.ChooseDataComboBox.setStyleSheet("background-color: rgb(196, 255, 246);")
        self.ChooseDataComboBox.setObjectName("ChooseDataComboBox")
        self.ChooseDataComboBox.addItem("Employees")
        self.ChooseDataComboBox.addItem("Clients")
        self.ChooseDataComboBox.addItem("Pharmacies")
        self.ChooseDataComboBox.addItem("Products")
        self.ChooseDataComboBox.addItem("Suppliers")
        self.ChooseDataComboBox.addItem("Orders")
        self.EditDataTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EditDataTextEdit.setGeometry(QtCore.QRect(860, 580, 241, 41))
        self.EditDataTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.EditDataTextEdit.setLineWidth(21)
        self.EditDataTextEdit.setObjectName("EditDataTextEdit")
        self.DataBaseTable = QtWidgets.QTableWidget(self.centralwidget)
        self.DataBaseTable.setGeometry(QtCore.QRect(20, 60, 821, 611))
        self.DataBaseTable.setStyleSheet("background-color: rgb(255, 230, 229);")
        self.DataBaseTable.setRowCount(15)
        self.DataBaseTable.setColumnCount(10)
        self.DataBaseTable.setObjectName("DataBaseTable")
        self.ShowDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShowDataButton.setGeometry(QtCore.QRect(890, 70, 191, 28))
        self.ShowDataButton.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 175, 175);")
        self.ShowDataButton.setObjectName("ShowDataButton")
        self.EditDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.EditDataButton.setGeometry(QtCore.QRect(860, 630, 241, 28))
        self.EditDataButton.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 175, 175);")
        self.EditDataButton.setObjectName("EditDataButton")
        self.InsertLabelEdit = QtWidgets.QLabel(self.centralwidget)
        self.InsertLabelEdit.setGeometry(QtCore.QRect(860, 530, 201, 31))
        self.InsertLabelEdit.setStyleSheet("color: rgb(255, 0, 0);")
        self.InsertLabelEdit.setWordWrap(True)
        self.InsertLabelEdit.setObjectName("InsertLabelEdit")
        self.DeleteDataTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.DeleteDataTextEdit.setGeometry(QtCore.QRect(860, 370, 241, 41))
        self.DeleteDataTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.DeleteDataTextEdit.setLineWidth(21)
        self.DeleteDataTextEdit.setObjectName("DeleteDataTextEdit")
        self.DeleteDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteDataButton.setGeometry(QtCore.QRect(860, 420, 241, 28))
        self.DeleteDataButton.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 175, 175);")
        self.DeleteDataButton.setObjectName("DeleteDataButton")
        self.AddDataTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.AddDataTextEdit.setGeometry(QtCore.QRect(860, 180, 241, 41))
        self.AddDataTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.AddDataTextEdit.setLineWidth(21)
        self.AddDataTextEdit.setObjectName("AddDataTextEdit")
        self.AddDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddDataButton.setGeometry(QtCore.QRect(860, 230, 241, 28))
        self.AddDataButton.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 175, 175);")
        self.AddDataButton.setObjectName("AddDataButton")
        self.InsertLabelAdd = QtWidgets.QLabel(self.centralwidget)
        self.InsertLabelAdd.setGeometry(QtCore.QRect(860, 110, 231, 61))
        self.InsertLabelAdd.setStyleSheet("color: rgb(255, 0, 0);")
        self.InsertLabelAdd.setWordWrap(True)
        self.InsertLabelAdd.setObjectName("InsertLabelAdd")
        self.InsertLabelDelete = QtWidgets.QLabel(self.centralwidget)
        self.InsertLabelDelete.setGeometry(QtCore.QRect(860, 330, 241, 31))
        self.InsertLabelDelete.setStyleSheet("color: rgb(255, 0, 0);")
        self.InsertLabelDelete.setWordWrap(True)
        self.InsertLabelDelete.setObjectName("InsertLabelDelete")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EditDataTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.ShowDataButton.setText(_translate("MainWindow", "Show Data"))
        self.EditDataButton.setText(_translate("MainWindow", "Edit Data"))
        self.InsertLabelEdit.setText(_translate("MainWindow", "Please insert the data in format: \"id; value1; value2; etc.\""))
        self.DeleteDataTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.DeleteDataButton.setText(_translate("MainWindow", "Delete Data"))
        self.AddDataTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.AddDataButton.setText(_translate("MainWindow", "Add Data"))
        self.InsertLabelAdd.setText(_translate("MainWindow", "Please insert the data in format: \"value1; value2; etc.\" If you're adding a new employee, the last value shoul be the password."))
        self.InsertLabelDelete.setText(_translate("MainWindow", "Please insert the id of data you want to delete."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
