# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistrationWindow_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 675)
        MainWindow.setStyleSheet("background-color: rgb(255, 230, 229);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FirstNameTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.FirstNameTextEdit.setGeometry(QtCore.QRect(160, 80, 391, 31))
        self.FirstNameTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.FirstNameTextEdit.setLineWidth(21)
        self.FirstNameTextEdit.setObjectName("FirstNameTextEdit")
        self.LastNameTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LastNameTextEdit.setGeometry(QtCore.QRect(160, 130, 391, 31))
        self.LastNameTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.LastNameTextEdit.setLineWidth(21)
        self.LastNameTextEdit.setObjectName("LastNameTextEdit")
        self.PatronymicTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PatronymicTextEdit.setGeometry(QtCore.QRect(160, 180, 391, 31))
        self.PatronymicTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.PatronymicTextEdit.setLineWidth(21)
        self.PatronymicTextEdit.setObjectName("PatronymicTextEdit")
        self.GenderTextedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.GenderTextedit.setGeometry(QtCore.QRect(160, 230, 391, 31))
        self.GenderTextedit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.GenderTextedit.setLineWidth(21)
        self.GenderTextedit.setObjectName("GenderTextedit")
        self.BirthdayEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.BirthdayEdit.setGeometry(QtCore.QRect(160, 280, 391, 31))
        self.BirthdayEdit.setStyleSheet("background-color: rgb(255, 212, 181);")
        self.BirthdayEdit.setObjectName("BirthdayEdit")
        self.EmailTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EmailTextEdit.setGeometry(QtCore.QRect(160, 330, 391, 31))
        self.EmailTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.EmailTextEdit.setLineWidth(21)
        self.EmailTextEdit.setObjectName("EmailTextEdit")
        self.PhoneNumberTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PhoneNumberTextEdit.setGeometry(QtCore.QRect(160, 380, 391, 31))
        self.PhoneNumberTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.PhoneNumberTextEdit.setLineWidth(21)
        self.PhoneNumberTextEdit.setObjectName("PhoneNumberTextEdit")
        self.AddressTesxtEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.AddressTesxtEdit.setGeometry(QtCore.QRect(160, 430, 391, 31))
        self.AddressTesxtEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.AddressTesxtEdit.setLineWidth(21)
        self.AddressTesxtEdit.setObjectName("AddressTesxtEdit")
        self.RegistrationLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegistrationLabel.setGeometry(QtCore.QRect(120, 10, 351, 61))
        self.RegistrationLabel.setStyleSheet("font: 28pt \"Arial\";")
        self.RegistrationLabel.setObjectName("RegistrationLabel")
        self.FirstNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.FirstNameLabel.setGeometry(QtCore.QRect(50, 80, 91, 31))
        self.FirstNameLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.FirstNameLabel.setObjectName("FirstNameLabel")
        self.LastNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.LastNameLabel.setGeometry(QtCore.QRect(50, 130, 91, 31))
        self.LastNameLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.LastNameLabel.setObjectName("LastNameLabel")
        self.PatronymicLabel = QtWidgets.QLabel(self.centralwidget)
        self.PatronymicLabel.setGeometry(QtCore.QRect(50, 180, 91, 31))
        self.PatronymicLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.PatronymicLabel.setObjectName("PatronymicLabel")
        self.GenderLabel = QtWidgets.QLabel(self.centralwidget)
        self.GenderLabel.setGeometry(QtCore.QRect(50, 230, 91, 31))
        self.GenderLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.GenderLabel.setObjectName("GenderLabel")
        self.BirthdayLabel = QtWidgets.QLabel(self.centralwidget)
        self.BirthdayLabel.setGeometry(QtCore.QRect(50, 280, 91, 31))
        self.BirthdayLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.BirthdayLabel.setObjectName("BirthdayLabel")
        self.EmailLabel = QtWidgets.QLabel(self.centralwidget)
        self.EmailLabel.setGeometry(QtCore.QRect(50, 330, 91, 31))
        self.EmailLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.EmailLabel.setObjectName("EmailLabel")
        self.PhoneNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.PhoneNumberLabel.setGeometry(QtCore.QRect(40, 380, 121, 31))
        self.PhoneNumberLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.PhoneNumberLabel.setObjectName("PhoneNumberLabel")
        self.AddresLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddresLabel.setGeometry(QtCore.QRect(50, 430, 91, 31))
        self.AddresLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.AddresLabel.setObjectName("AddresLabel")
        self.PasswordTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PasswordTextEdit.setGeometry(QtCore.QRect(160, 480, 391, 31))
        self.PasswordTextEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 212, 181);\n"
"border-color: rgb(85, 0, 0);")
        self.PasswordTextEdit.setLineWidth(21)
        self.PasswordTextEdit.setObjectName("PasswordTextEdit")
        self.R_PasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.R_PasswordLabel.setGeometry(QtCore.QRect(50, 480, 91, 31))
        self.R_PasswordLabel.setStyleSheet("font: 75 10pt \"Arial\";")
        self.R_PasswordLabel.setObjectName("R_PasswordLabel")
        self.RequiredLabel = QtWidgets.QLabel(self.centralwidget)
        self.RequiredLabel.setGeometry(QtCore.QRect(0, 60, 91, 31))
        self.RequiredLabel.setStyleSheet("font: 75 8pt \"Arial\";")
        self.RequiredLabel.setObjectName("RequiredLabel")
        self.RegisterButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterButton.setGeometry(QtCore.QRect(140, 540, 271, 61))
        self.RegisterButton.setStyleSheet("background-color: rgb(255, 235, 84);\n"
"font: 75 18pt \"Arial\";")
        self.RegisterButton.setObjectName("RegisterButton")
        self.ErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.ErrorLabel.setGeometry(QtCore.QRect(70, 610, 861, 61))
        self.ErrorLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.FirstNameTextEdit.raise_()
        self.LastNameTextEdit.raise_()
        self.PatronymicTextEdit.raise_()
        self.GenderTextedit.raise_()
        self.BirthdayEdit.raise_()
        self.EmailTextEdit.raise_()
        self.PhoneNumberTextEdit.raise_()
        self.AddressTesxtEdit.raise_()
        self.RegistrationLabel.raise_()
        self.LastNameLabel.raise_()
        self.PatronymicLabel.raise_()
        self.GenderLabel.raise_()
        self.BirthdayLabel.raise_()
        self.EmailLabel.raise_()
        self.PhoneNumberLabel.raise_()
        self.AddresLabel.raise_()
        self.PasswordTextEdit.raise_()
        self.R_PasswordLabel.raise_()
        self.RequiredLabel.raise_()
        self.FirstNameLabel.raise_()
        self.RegisterButton.raise_()
        self.ErrorLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FirstNameTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.LastNameTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.PatronymicTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.GenderTextedit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.EmailTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.PhoneNumberTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.AddressTesxtEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.RegistrationLabel.setText(_translate("MainWindow", "REGISTRATION"))
        self.FirstNameLabel.setText(_translate("MainWindow", "First Name*"))
        self.LastNameLabel.setText(_translate("MainWindow", "Last Name*"))
        self.PatronymicLabel.setText(_translate("MainWindow", "Patronymic"))
        self.GenderLabel.setText(_translate("MainWindow", "Gender"))
        self.BirthdayLabel.setText(_translate("MainWindow", "Birthday*"))
        self.EmailLabel.setText(_translate("MainWindow", "Email*"))
        self.PhoneNumberLabel.setText(_translate("MainWindow", "Phone number*"))
        self.AddresLabel.setText(_translate("MainWindow", "Address"))
        self.PasswordTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.R_PasswordLabel.setText(_translate("MainWindow", "Password*"))
        self.RequiredLabel.setText(_translate("MainWindow", "Required*"))
        self.RegisterButton.setText(_translate("MainWindow", "REGISTER"))
        self.ErrorLabel.setText(_translate("MainWindow", "\'Тут будет выводиться сообщение о том, что что-то неправильно указано\'"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_RegistrationWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
