# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserWindow_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(954, 599)
        UserWindow.setStyleSheet("background-color: rgb(255, 230, 229);")
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MyOrdersButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.MyOrdersButton_2.setGeometry(QtCore.QRect(40, 540, 191, 28))
        self.MyOrdersButton_2.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 175, 175);")
        self.MyOrdersButton_2.setObjectName("MyOrdersButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 130, 871, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 591, 41))
        self.label.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 591, 41))
        self.label_2.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "MainWindow"))
        self.MyOrdersButton_2.setText(_translate("UserWindow", "New order"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UserWindow", "Order#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UserWindow", "Client#"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UserWindow", "Order Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UserWindow", "Delivery method"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("UserWindow", "Weight"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("UserWindow", "Payment method"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("UserWindow", "Payment Amount"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("UserWindow", "Order date"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("UserWindow", "Email"))
        self.label.setText(_translate("UserWindow", "Hello,"))
        self.label_2.setText(_translate("UserWindow", "This is your order history. "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserWindow = QtWidgets.QMainWindow()
    ui = Ui_UserWindow()
    ui.setupUi(UserWindow)
    UserWindow.show()
    sys.exit(app.exec_())
